
create table car (id int8 generated by default as identity, model varchar(255), owner_id int8, primary key (id));
create table customer_cars (customer_id int8 not null, cars_id int8 not null, primary key (customer_id, cars_id));

alter table if exists customer_cars add constraint UQ_customer_cars_cars_id unique (cars_id);
alter table if exists car add constraint FK_car_owner_id foreign key (owner_id) references customer;
alter table if exists customer_cars add constraint FK_customer_cars_cars_id foreign key (cars_id) references car;
alter table if exists customer_cars add constraint FK_customer_cars_customer_id foreign key (customer_id) references customer;